import { ChatMessage, ChatReaction, ChatReactionType } from "./types/chat";
import { User } from "./types/user";

export const FakeUsers: User[] = [
  {
    id: "1",
    username: "zero",
    firstName: "Hassan",
    lastName: "karrach",
    isOnline: true,
    lastSeen: new Date(),
    avatar: "www.example.com/avatar1.png",
    banner: "www.example.com/banner1.png",
    bio: "stupid",
    createdAt: new Date(),
    updatedAt: new Date(),
    totalGames: 100,
    wins: 70,
    losses: 30,
    rank: 1,
    level: 10,
    friends: ["2", "3"],
    blockedUsers: ["4"],
    twoFactorEnabled: true,
    isVerified: true,
    walletBalance: 1000,
  },
  {
    id: "2",
    username: "one",
    firstName: "John",
    lastName: "Doe",
    isOnline: false,
    lastSeen: new Date(),
    avatar: "www.example.com/avatar2.png",
    banner: "www.example.com/banner2.png",
    bio: "Hello World!",
    createdAt: new Date(),
    updatedAt: new Date(),
    totalGames: 200,
    wins: 150,
    losses: 50,
    rank: 2,
    level: 20,
    friends: ["1", "3"],
    blockedUsers: [],
    twoFactorEnabled: false,
    isVerified: true,
    walletBalance: 500,
  },
  {
    id: "3",
    username: "two",
    firstName: "Jane",
    lastName: "Smith",
    isOnline: true,
    lastSeen: new Date(),
    avatar: "www.example.com/avatar3.png",
    banner: "www.example.com/banner3.png",
    bio: "Loves gaming!",
    createdAt: new Date(),
    updatedAt: new Date(),
    totalGames: 300,
    wins: 200,
    losses: 100,
    rank: 3,
    level: 30,
    friends: ["1", "2"],
    blockedUsers: [],
    twoFactorEnabled: true,
    isVerified: false,
    walletBalance: 750,
  },
  {
    id: "4",
    username: "three",
    firstName: "Alice",
    lastName: "Johnson",
    isOnline: false,
    lastSeen: new Date(),
    avatar: "www.example.com/avatar4.png",
    banner: "www.example.com/banner4.png",
    bio: "Gamer and streamer",
    createdAt: new Date(),
    updatedAt: new Date(),
    totalGames: 400,
    wins: 300,
    losses: 100,
    rank: 4,
    level: 40,
    friends: ["1", "2", "3"],
    blockedUsers: ["5"],
    twoFactorEnabled: false,
    isVerified: true,
    walletBalance: 1200,
  },
];

export const FakeChatMessages: ChatMessage[] = [
  {
    from: FakeUsers[0],
    date: new Date(),
    message: "Hello, how are you?",
    isRead: true,
    reactions: [
      {
        from: FakeUsers[1],
        type: "like" as ChatReactionType,
      },
      {
        from: FakeUsers[2],
        type: "laugh" as ChatReactionType,
      },
    ],
  },
  {
    from: FakeUsers[1],
    date: new Date(),
    message: "I'm good, thanks! How about you?",
    isRead: false,
    reactions: [],
  },
  {
    from: FakeUsers[2],
    date: new Date(),
    message: "Let's play a game later!",
    isRead: true,
    reactions: [
      {
        from: FakeUsers[0],
        type: "like" as ChatReactionType,
      },
    ],
  },
];
